services:
  voices:
    container_name: voices
    image: usdotfhwastoldev/voices:pilot2-event2-latest
    tty: true
    ipc: "host"
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_CONTAINER_IMAGE=voices
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
      - VUG_SCENARIO_CONFIG_FILE=${VUG_SCENARIO_CONFIG_FILE}
      - VUG_VPN_LOCAL_ADDRESS=${VUG_VPN_LOCAL_ADDRESS}
      - VUG_VPN_EM_ADDRESS=${VUG_VPN_EM_ADDRESS}
    env_file:
      - ${HOME}/.voices_site_config
      - ${HOME}/.voices_scenario_config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${VUG_LOCAL_VOICES_POC_PATH}:/home/voices-poc